server:
  port: 9092
spring:
  profiles: peer2
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:9091/eureka/