server:
  port: 9091
spring:
  profiles: peer1
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:9092/eureka/